---
- name: Get hostname and IP address of Alpine hosts
  hosts: web_servers
  connection: local
  gather_facts: yes
  tasks:
    # - name: Display hostname and IP address
    #   debug:
    #     msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"

    - name: Print debug message
      debug:
        msg: Hello, world!

    - name: Ping site
      shell: ping -c 1 -w 2 ayphu.com
      register: ping_result

    - name: Ping result
      debug:
        msg: "{{ ping_result.stdout_lines }}"

    - name: Trigger webhook with increased timeout
      uri:
        url: "https://alertmanager_gotify.ayphu.com/gotify_webhook?token=Ao.VjP3D-NMVwkC"
        method: POST
        status_code: 200
        return_content: yes
        validate_certs: no
      register: webhook_response

    - name: Debug webhook response
      debug:
        var: webhook_response.content
